services:
  - type: web
    name: barograma-backend
    env: node
    buildCommand: npm install --include=dev && npx prisma generate && npx prisma db push && npx ts-node prisma/seed.ts && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    rootDir: backend


  - type: web
    name: barograma-frontend
    env: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: barograma-backend
          envVarKey: RENDER_EXTERNAL_URL
    rootDir: frontend
